name: Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GodotExport
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
      - name: Check Repo
        run: ls && pwd && ls ./build && ls ./build/web && ls /home/runner/.local && ls /home/runner/.local/share && ls /home/runner/.local/share/godot && ls /home/runner/.local/share/godot/builds && echo _____________________ && ls /home/runner/.local/share/godot/builds/Web
      - name: Move Build
        run: cp -r /home/runner/.local/share/godot/builds/Web/ /home/runner/work/SyntaxSoup/SyntaxSoup/build/web/ && ls build/web
      - name: Web Deployment
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SYNTAX_SOUP }}'
          projectId: syntax-soup
          channelId: live
      - name: Export Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Builds
          path: /home/runner/.local/share/godot/builds
